# Generated by Django 5.2.4 on 2025-08-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cik', models.CharField(db_index=True, max_length=10)),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('form_type', models.CharField(max_length=50)),
                ('period_end', models.DateField()),
                ('local_path', models.CharField(max_length=500)),
                ('format', models.CharField(max_length=20)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('parse_ok', models.BooleanField(default=False)),
            ],
        ),
    ]
