# Generated by Django 5.2.4 on 2025-08-09 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('isin', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('figi', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('listing_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=100)),
                ('report_date', models.DateField()),
                ('eps_basic', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('eps_diluted', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('net_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screener.company')),
            ],
        ),
    ]
