name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣  Chequea el código del repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣  Configura Miniconda y crea el entorno screener-env
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Mambaforge          # mamba = mucho más rápido
          activate-environment: screener-env
          environment-file: environment.yaml
          auto-update-conda: true
          use-mamba: true

      # 3️⃣  Caché de la carpeta pkgs de conda
      - name: Cache Conda
        uses: actions/cache@v4
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ hashFiles('environment.yaml') }}
          restore-keys: |
            ${{ runner.os }}-conda-

      # 4️⃣  Ejecuta tests + cobertura
      - name: Run tests with coverage
        shell: bash -l {0}              # importante: -l para activar el entorno
        run: |
          pytest -q \
            --cov=app \
            --cov-report=xml \
            --cov-report=term \
            --cov-fail-under=95

      # 5️⃣  Sube coverage.xml como artefacto
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
